name: Skillzzy_bot_json_check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate JSON files
        run: |
          echo "Checking JSON syntax..."
          find . -type f -name "*.json" | while read file; do
            echo "Validating $file"
            jq empty "$file"
          done
